apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: blobs.raker22.com
spec:
  group: raker22.com
  version: v1alpha1
  names:
    kind: Blob
    plural: blobs
  scope: Namespaced